# Generated by Django 4.0 on 2022-01-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=15, null=True)),
                ('slug', models.SlugField(max_length=15, null=True, unique=True)),
            ],
        ),
    ]
