# Generated by Django 4.0 on 2022-01-08 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_teamsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('product_picture', models.ImageField(default='products/product-hunt-turkey-logo.jpg', upload_to='products/%Y/%m/%d/')),
                ('product_ph_link', models.CharField(max_length=250)),
                ('product_website', models.CharField(blank=True, max_length=250, null=True)),
                ('product_twitter', models.CharField(blank=True, max_length=250, null=True)),
                ('product_owner_twitter', models.CharField(blank=True, max_length=250, null=True)),
                ('product_launch_date', models.DateField()),
                ('product_hunt_votes', models.CharField(blank=True, default=0, max_length=6, null=True)),
                ('is_published_telegram', models.BooleanField(default=False)),
                ('is_published_twitter', models.BooleanField(default=False)),
                ('is_published_mail', models.BooleanField(default=False)),
                ('is_published_linkedin', models.BooleanField(default=False)),
                ('is_avaliable', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.city')),
                ('product_team_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.teamsize')),
            ],
        ),
    ]
