# Generated by Django 4.0 on 2022-01-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(default='static/images/producthuntturkey-logo.png', upload_to='products/%Y/%m/%d/'),
        ),
    ]
