# Generated by Django 4.0 on 2022-01-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(default='default/producthuntturkey-logo.png', upload_to='products/%Y/%m/%d/'),
        ),
    ]
