# Generated by Django 4.0 on 2022-02-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True, null=True, verbose_name='product_description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_launch_date',
            field=models.DateField(verbose_name='product_launch_date'),
        ),
    ]
