# Generated by Django 4.0 on 2022-02-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttranslation',
            name='product_launch_date',
        ),
        migrations.AddField(
            model_name='product',
            name='product_launch_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
