# Generated by Django 4.0 on 2022-02-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_producttranslation_product_launch_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_ph_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
