# Generated by Django 4.0 on 2022-06-28 15:49

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('launchcalendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launchcalendar',
            name='product_about_en',
        ),
        migrations.RemoveField(
            model_name='launchcalendar',
            name='product_about_tr',
        ),
        migrations.AlterField(
            model_name='launchcalendar',
            name='status',
            field=models.CharField(choices=[('w', 'İnceleme Bekliyor'), ('p', 'Onaylandı'), ('d', 'Yayınlanmayacak')], default='w', max_length=1),
        ),
        migrations.CreateModel(
            name='LaunchCalendarTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('product_description', models.TextField(blank=True, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='launchcalendar.launchcalendar')),
            ],
            options={
                'verbose_name': 'launch calendar Translation',
                'db_table': 'launchcalendar_launchcalendar_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases = (parler.models.TranslatableModel, models.Model),
        ),
    ]
