# Generated by Django 4.0 on 2022-01-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addyourstartup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addyourstartuparea',
            name='product_launch_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
