# Generated by Django 4.0 on 2022-02-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addyourstartup', '0002_alter_addyourstartuparea_product_launch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='addyourstartuparea',
            name='status',
            field=models.CharField(choices=[('w', 'İnceleme Bekliyor'), ('p', 'Product Tablosuna Eklendi'), ('d', 'Yayınlama')], default='w', max_length=1),
        ),
    ]
