# Generated by Django 4.0 on 2022-06-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addyourstartup', '0003_addyourstartuparea_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='addyourstartuparea',
            name='product_future_launch_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
